name: Remove a release
description: Delete a release and its screenshots from the website.
title: "[remove] "
labels: ["release", "remove"]
body:
  - type: input
    id: device
    attributes:
      label: Device codename
      placeholder: santoni
    validations:
      required: true
  - type: input
    id: release_id
    attributes:
      label: Release id
      description: The last part of the release URL.
      placeholder: miui-12-0-3
    validations:
      required: true
